# Generated by Django 4.0.6 on 2022-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='trigger',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
